files:
  - source: /Loop/Base.lproj/Localizable.strings
    translation: /Loop/%osx_locale%.lproj/Localizable.strings
  - source: /Loop/en.lproj/Main.strings
    translation: /Loop/%osx_locale%.lproj/Main.strings
  - source: /WatchApp Extension/Base.lproj/Localizable.strings
    translation: /WatchApp Extension/%osx_locale%.lproj/Localizable.strings
  - source: /WatchApp/en.lproj/Interface.strings
    translation: /WatchApp/%osx_locale%.lproj/Interface.strings
